language: python
python:
- "2.7"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
install:
- pip install -r requirements.txt
- pip install -r requirements-test.txt
env:
- RUOTE_ROOT=https://preapi.teamjamon.com
script:
- nosetests --with-coverage --cover-package=alfredo --stop
after_success:
- coveralls
deploy:
  provider: pypi
  user: robermorales
  password:
    secure: OovDKTJraZdQRqCmqFM3O03emqxsXeIs9o5m8ttC+fhDCXSEDmQNO/XepXCunPG778JhfQCy9wRO3qbXAOj9kZu2uELouA9P5SuLwOHjb83vk6bcppyH9XzWOOe8IUkx7/LoSDRDIYJovSGcqmdR9wnk0AQ0sQEM0oSoxzKsvvNqKkF+QuOEz+UerZupYZdxWZpTTEaBJO9lket8JsDuNE67UQwlBBOfRTxit8pezQ8vWHHYGa+y0/npGRGaoH3aOEZT2erLNoR2th4YQfB+RwApdTyut5RDeJB9FZSzzO2qIhEH6nEfYTkNYDPvy1PhKZSoYmlFuS7dv+WPfH7BQNEenc3TLV4078vYUy8foHsf+O+8byYUBExWIxqpeF4aaz1+dkpm5Cv1S2Ljz59xui/wnlJxvgXx7eb6ieRlRNJkT3WKrQ2CUL8EiRiWHyx8M7ZyDRECsO6c4t23fzm+JDhj2D6hFq3Fvc3Nm1am0jfd+Mn+muLEZIq1OhmablflRfFOEfYdvwYFGRp5spvI4DVGONiz2MPfE5ojAO2TB2NqYG+0+I+BoP1X5lZHNT8yNBey01ipTJ7YTmFJIX5AALzEFTcfD+mY+YwryATVAC2mBN/Ym/64xyiUZT7AXT009FdGF+BG9vE7CfkffZN/wi+u1+kILm/CVPJLGJSMxD0=
  distributions: bdist_wheel
  on:
    python: 3.6
    repo: rstorsauce/alfredo-python-sdk
    branch: develop
